# Configure which items show in the nav bar
navbar:
  schedule: true
  hack-ideas: true
  prizing: false
  sponsors: true
  about: true
  faq: true
  resources: true
  register: false

homepage:
  # The timeline options are: pre-registration, registration, live, post-registration
  timeline: registration

livesite:
    show-livesite: false
    show-judging-info: false
    show-travel-info: false

eventData:
  # Hackathon data
  fullDate: Feb 26th and 27th, 2022
  date:
    month: February
    firstDay: 26
    secondDay: 27
    year: 2022
  # Interest form url
  # interestForm: https://forms.gle/LrmB5fpVQbaSy6To6
  # Submissions url
  submissions: https://revuc-x.devpost.com/submissions

MLH:
  # Change this to true when MLH accepts our hackathon application
  showBanner: false
  # Be sure to update this for the current year, check the MLH website for the code for this badge
  banner: <a id="mlh-trust-badge" style="display:block;max-width:100px;min-width:60px;position:fixed;right:50px;top:0;width:10%;z-index:10000" href="https://mlh.io/seasons/2021/events?utm_source=na-hackathon&utm_medium=TrustBadge&utm_campaign=2021-season&utm_content=white" target="_blank"><img src="https://s3.amazonaws.com/logged-assets/trust-badge/2021/mlh-trust-badge-2021-white.svg" alt="Major League Hacking 2021 Hackathon Season" style="width:100%"></a>
